// <auto-generated />
using System;
using DotNet_Quick_ref_all.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNet_Quick_ref_all.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20251126061711_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNet_Quick_ref_all.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Name = "Work"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Home"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Office"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Errands"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Urgent"
                        });
                });

            modelBuilder.Entity("DotNet_Quick_ref_all.Domain.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            IsDone = false,
                            Title = "Email boss"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            IsDone = true,
                            Title = "Organize desk"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            IsDone = false,
                            Title = "Update report"
                        });
                });

            modelBuilder.Entity("DotNet_Quick_ref_all.Domain.TodoItem", b =>
                {
                    b.HasOne("DotNet_Quick_ref_all.Domain.Category", "Category")
                        .WithMany("TodoItems")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DotNet_Quick_ref_all.Domain.Category", b =>
                {
                    b.Navigation("TodoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
